// // <auto-generated />
// using System;
// using Billy_BE.Models;
// using Microsoft.EntityFrameworkCore;
// using Microsoft.EntityFrameworkCore.Infrastructure;
// using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

// #nullable disable

// namespace Billy_BE.Migrations
// {
//     [DbContext(typeof(BillyContext))]
//     partial class BillyContextModelSnapshot : ModelSnapshot
//     {
//         protected override void BuildModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

//             modelBuilder.Entity("Billy_BE.Models.GamePlayed", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("PlayerOneElo")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("PlayerOneId")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("PlayerTwoElo")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("PlayerTwoId")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("TenantId")
//                         .HasColumnType("INTEGER");

//                     b.Property<DateTime>("TimeOfPlay")
//                         .HasColumnType("TEXT");

//                     b.Property<int>("WinnerId")
//                         .HasColumnType("INTEGER");

//                     b.HasKey("Id");

//                     b.HasIndex("PlayerOneId");

//                     b.HasIndex("PlayerTwoId");

//                     b.HasIndex("WinnerId");

//                     b.ToTable("GamesPlayed");
//                 });

//             modelBuilder.Entity("Billy_BE.Models.GamePlayedMultiplePlayers", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("TenantId")
//                         .HasColumnType("INTEGER");

//                     b.Property<DateTime>("TimeOfPlay")
//                         .HasColumnType("TEXT");

//                     b.HasKey("Id");

//                     b.ToTable("GamePlayedMultiplePlayers");
//                 });

//             modelBuilder.Entity("Billy_BE.Models.Player", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("CurrentWinStreak")
//                         .HasColumnType("INTEGER");

//                     b.Property<DateTime>("DateCreated")
//                         .HasColumnType("TEXT");

//                     b.Property<int>("GamesPlayed")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("LongestWinStreak")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("Losses")
//                         .HasColumnType("INTEGER");

//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasColumnType("TEXT");

//                     b.Property<int>("Rating")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("TenantId")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("Winrate")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("Wins")
//                         .HasColumnType("INTEGER");

//                     b.HasKey("Id");

//                     b.ToTable("Players");
//                 });

//             modelBuilder.Entity("Billy_BE.Models.PlayerSnapshot", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("EloChange")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("EloPost")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("EloPre")
//                         .HasColumnType("INTEGER");

//                     b.Property<int?>("GamePlayedMultiplePlayersId")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("Place")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("PlayerId")
//                         .HasColumnType("INTEGER");

//                     b.Property<DateTime>("SnapshotTime")
//                         .HasColumnType("TEXT");

//                     b.HasKey("Id");

//                     b.HasIndex("GamePlayedMultiplePlayersId");

//                     b.HasIndex("PlayerId");

//                     b.ToTable("PlayerSnapshots");
//                 });

//             modelBuilder.Entity("Tenant", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("INTEGER");

//                     b.Property<DateTime>("CreatedAt")
//                         .HasColumnType("TEXT");

//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasColumnType("TEXT");

//                     b.Property<string>("Subdomain")
//                         .IsRequired()
//                         .HasColumnType("TEXT");

//                     b.HasKey("Id");

//                     b.ToTable("Tenants");
//                 });

//             modelBuilder.Entity("Billy_BE.Models.GamePlayed", b =>
//                 {
//                     b.HasOne("Billy_BE.Models.Player", "PlayerOne")
//                         .WithMany()
//                         .HasForeignKey("PlayerOneId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.HasOne("Billy_BE.Models.Player", "PlayerTwo")
//                         .WithMany()
//                         .HasForeignKey("PlayerTwoId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.HasOne("Billy_BE.Models.Player", "Winner")
//                         .WithMany()
//                         .HasForeignKey("WinnerId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("PlayerOne");

//                     b.Navigation("PlayerTwo");

//                     b.Navigation("Winner");
//                 });

//             modelBuilder.Entity("Billy_BE.Models.PlayerSnapshot", b =>
//                 {
//                     b.HasOne("Billy_BE.Models.GamePlayedMultiplePlayers", "GamePlayedMultiplePlayers")
//                         .WithMany("PlayerSnapshots")
//                         .HasForeignKey("GamePlayedMultiplePlayersId");

//                     b.HasOne("Billy_BE.Models.Player", "Player")
//                         .WithMany()
//                         .HasForeignKey("PlayerId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("GamePlayedMultiplePlayers");

//                     b.Navigation("Player");
//                 });

//             modelBuilder.Entity("Billy_BE.Models.GamePlayedMultiplePlayers", b =>
//                 {
//                     b.Navigation("PlayerSnapshots");
//                 });
// #pragma warning restore 612, 618
//         }
//     }
// }
